package com.associations.models;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;


@Entity
@Table(name="USER_DETAILS")
public class UserDetails {
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="USER_ID")
	private long userId;
	
	@Column(name="NAME")
	private String name;
	
	@OneToMany(mappedBy="user")
//	//@JoinTable annotation is used to rename tables generated by hibernate to map tables
//	@JoinTable(name="USER_VEHICLE",
//	joinColumns=@JoinColumn(name="USER_ID"),
//	inverseJoinColumns=@JoinColumn(name="VEHICLE_ID"))
	
	private List<Vehicle> vehicles;

	//Getters and setters
	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Vehicle> getVehicles() {
		return vehicles;
	}

	public void setVehicles(List<Vehicle> vehicles) {
		this.vehicles = vehicles;
	}

	
	
	
	

}
